version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8002
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017" #overriding appsettings conn string
    depends_on:
      - shopping.db
    ports:
      - "8007:8002" #direct 8007(port host): to 8002(port container)

  shopping.client:
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8006
      - "ShoppingAPIUrl=http://shoppingapi:8002"
    depends_on:
      - shopping.db
      - shopping.api
    ports:
      - "8005:8006" #direct 8005(local port in host machine): to 8006(port inside container)

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017" #direct 27017(local port in host machine): to 27017(port inside container)
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db